### ISSUE TITLE
繁簡轉換

### ISSUE THREAD

**Issue by NeKoOuO** [Sakura1618/dsp-kb#1]
Hi!👋 我覺得這個項目很棒 如果有機會的話希望可以加入簡轉繁的功能 這樣就再好不過了 謝謝😊
Web:
https://docs.zhconvert.org/
API:
https://api.zhconvert.org/

**Comment by Sakura1618** [comment]
88b1341 已添加對繁體中文（zh-TW）的支持

**Comment by NeKoOuO** [comment]
Thx
